import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import Image from "next/image";
import Footer from "./footer";
import Link from "next/link";
import { currentUser } from "@clerk/nextjs/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  const userRole = user?.publicMetadata?.role;
  const profileHref = `/${userRole}/profile`;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          {/* 3-Column Grid: Left spacer, Center Navbar, Right Auth buttons */}
          <header className="sticky top-0 z-50 grid grid-cols-[1fr_auto_1fr] items-center px-6 bg-white shadow">
            {/* Left side (can be empty or hold a Logo) */}
            <div>
              <Link href="/">
                <Image
                  src={"/next.svg"}
                  alt="Next.JS"
                  width={100}
                  height={50}
                />
              </Link>
            </div>

            {/* Center: Navbar locked to absolute center */}
            <div className="justify-self-center">
              <Navbar />
            </div>

            {/* Right side: Auth buttons aligned to the far right */}
            <div className="justify-self-end flex items-center gap-3">
              <Show when="signed-out">
                <SignInButton />
                <SignUpButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 px-4 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </Show>
              <Show when="signed-in">
                <UserButton
                  userProfileMode="navigation"
                  userProfileUrl={profileHref}
                />
              </Show>
            </div>
          </header>

          {children}
          <Footer />
        </ClerkProvider>
      </body>
    </html>
  );
}
